import Head from "next/head";
 import {
   AiFillLinkedin,
   AiFillGithub
 } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/selfie4.png";
import dna from "../public/dna2.png";
import calculator from "../public/calc.png";
import cloud from "../public/cloud.png";
import Image from "next/image";


export default function Home() {
    const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Veerpal Shah Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     <main className="bg-stone-100 px-10 md:px-20 lg:px-40 dark:bg-gray-900">

      <section className="min-h-screen">

        <nav className="py-10 mb-2 flex justify-between">
        <div class="h-12 w-20 rounded-md dark:bg-gradient-to-r dark:from-amber-500 dark:via-rose-400 dark:to-pink-400 bg-gradient-to-r from-sky-600 via-cyan-700 to-sky-900 p-1">
    <div class="flex h-full w-full items-center justify-center bg-stone-300 dark:bg-gray-800 back">
    <h1 className="text-4xl font-burtons dark:text-pink-200">vps</h1>

    </div>
  </div>
          <ul className="flex items-center ">
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-white hover:scale-125"/>
            </li>
            <li className="hover:scale-110 font- font-semibold"><a className="dark:bg-gradient-to-r dark:from-purple-600 dark:to-amber-600 bg-gradient-to-r from-blue-400 via-sky-600 via-sky-800 to-cyan-700 text-white px-4 py-2 rounded-md ml-8" href="/resume.pdf">Resume</a></li>
          </ul>
        </nav>
        <div className="text-left p-10 py-10">
          <h2 className="text-5xl py-2 px-0 text-zinc-800 dark:text-purple-500 font-helvetica font-extrabold md:text-6xl ">About</h2>
          <h3 className="text-2xl py-2 px-0 md:text-3xl font-helvetica font-extrabold dark:text-white">Veerpal Shah.</h3>
          <p className="text-md pt-5 leading-8 text-gray-700 md:text-xl  mx-auto dark:text-indigo-300">Hello, World! I am an innovation-driven, versatile Computer and Information Sciences student passionate about developing systems that help users navigate the digital landscape seamlessly, while pushing existing boundaries in technology down to create solutions that greatly impact society. </p>  
          <p className="text-md py-0 leading-8 text-gray-700 md:text-xl mx-auto dark:text-indigo-400">Welcome to my portofolio website!</p>
        </div>
        <div className="flex justify-center gap-16">
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-500 hover:scale-150" >
            <a href="https://github.com/veerpal-shah">
              <AiFillGithub />
            </a>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-500 hover:scale-150" >
            <a href="https://www.linkedin.com/in/veerpal-shah/">
              <AiFillLinkedin />
            </a>
          </div>
        </div>
        <div className="relative mx-auto bg-gradient-to-b from-sky-300 dark:from-fuchsia-300 dark:to-gray-200 rounded-full w-80 h-80 mt-10 mb-10 overflow-hidden md:h-96 md:w96">
          <Image src={deved} layout="fill" objectFit="cover"/>
        </div>
      </section>



      <section>
        <div>
          <h3 className="text-2xl py-2 md:text-3xl font-helvetica font-extrabold dark:text-stone-300">Signature Proficiencies & Projects.</h3>
          <p className="text-md py-5 leading-8 text-gray-700 md:text-xl mx-auto dark:text-indigo-300">
            Since the start I have always been passionate about working in Computer Science and hence I worked on learning as much as I can. These are some of the <span className="text-pink-600"> projects </span> I made on my path of learning!
          </p>
          <p className="text-md py-5  leading-8 text-gray-700 md:text-xl  mx-auto dark:text-indigo-400">
            I specialize in various fields including <span className="text-pink-600">AI Research</span>, <span className="text-pink-600">Software Development </span> & <span className="text-pink-600">Data Analysis, Scraping and Visualization</span>. 
          </p>
        </div>
        <div className="lg:flex gap-10 dark:text-green-300">
    
          <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-stone-200 dark:bg-gray-800">
            <a href="https://github.com/veerpal-shah" className="text-5xl float-right gap-16 py-3 text-gray-500 hover:scale-125">
              <AiFillGithub />
            </a>
            <Image src={calculator} width={'100'} height={'100'}/>
            <h3 className="text-lg font-medium pt-8 pb-2 dark:text-stone-300">GUI Calculator</h3>
            <p className="py-2 dark:text-indigo-400">A simple calculator capable of performing multiple arithmetic operations including finding powers and roots of numbers. Used the Swing Framework to create a GUI.</p>
            <h4 className="py-4 dark:text-indigo-300">Tools used:</h4>
            <p className="text-gray-700 py-1 dark:text-pink-600">Java</p>
            <p className="text-gray-700 py-1 dark:text-pink-600">Model-View-Controller Design</p>
            <p className="text-gray-700 py-1 dark:text-pink-600">Command Line</p>
            <p className="text-gray-700 py-1 dark:text-pink-600">Swing Framework</p>
          </div>

          <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-stone-200 dark:bg-gray-800">
            <a href="https://github.com/veerpal-shah" className="text-5xl float-right gap-16 py-3 text-gray-500 hover:scale-125">
              <AiFillGithub />
            </a>
            <Image src = {dna} width={'100'} height={'100'}/>
            <h3 className="text-lg font-medium pt-8 pb-2 dark:text-stone-300">Calmodulin Scraper</h3>
            <p className="py-2 dark:text-indigo-400">This is a webscraper that extracts specific data about amino acids with certain sizes; this data is redirected to a database.</p>
            <h4 className="py-4 dark:text-indigo-300">Tools used:</h4>
            <p className="text-gray-700 py-1 dark:text-pink-600">Web Scraping</p>

            <p className="text-gray-700 py-1 dark:text-pink-600">Python</p>
            
            <p className="text-gray-700 py-1 dark:text-pink-600">pandas</p>
            <p className="text-gray-700 py-1 dark:text-pink-600">BeautifulSoup</p>
            <p className="text-gray-700 py-1 dark:text-pink-600">HTTP requests (GET and POST)</p>

          </div>
      
          <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-stone-200 dark:bg-gray-800">
            <a href="https://github.com/veerpal-shah" className="text-5xl float-right gap-16 py-3 text-gray-500 hover:scale-125">
              <AiFillGithub />
            </a>
            <Image src = {cloud} width={'100'} height={'100'}/>
            <h3 className="text-lg font-medium pt-8 pb-2 dark:text-stone-300">Word Cloud</h3>
            <p className="py-2 dark:text-indigo-400">A webapp that parses a file to extract all the words in it, and arranges them in the shape of a cloud on a webpage.</p>
            <h4 className="py-4 dark:text-indigo-300">Tools used:</h4>
            <p className="text-gray-700 py-1 dark:text-pink-600">Java</p>
            <p className="text-gray-700 py-1 dark:text-pink-600">Map and Set DS</p>
            <p className="text-gray-700 py-1 dark:text-pink-600">File Manipulation</p>
            <p className="text-gray-700 py-1 dark:text-pink-600">Sorting Machine</p>
            <p className="text-gray-700 py-1 dark:text-pink-600">HTML and CSS</p>

          </div>

          
        </div>
      </section>
      <section className="bg-stone-200 dark:bg-gray-800 rounded-md py-9">
        <div className="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
            <h2 className="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Contact Me</h2>
            <p className="mb-8 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl">Got a question? Want to contact me? Let me know!</p>
            <form action="#" className="space-y-8">
                <div>
                    <label htmlFor="email" className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your email</label>
                    <input type="email" id="email" className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="john@appleseed.com" required />
                </div>
                <div>
                    <label htmlFor="subject" className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Subject</label>
                    <input type="text" id="subject" className="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="Let me know how I can help you" required />
                </div>
                <div className="sm:col-span-2">
                    <label htmlFor="message" className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">Your message</label>
                    <textarea id="message" rows="6" className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Leave a comment..."></textarea>
                </div>
                <button type="submit" className="py-3 px-5 text-sm font-medium text-center text-black dark:text-white shadow-lg rounded-lg bg-stone-400 dark:bg-gray-700 sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-800 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Send message</button>
            </form>
        </div>
      </section>

      

     </main>
    </div>
  );
}
